export const engineers = [
  'Alan Mulligan',
  'Alex Sim',
  'Arkadiusz Bielecki',
  'Barrie Dolan',
  'Barry Noctor',
  'Brendan Hanna',
  'Brian Harte',
  'Brian Murphy',
  "Brian O'Reilly",
  'Claire Corcoran',
  'Colm Brennan',
  'Chandu Prakash',
  'Daniel Stenhouse',
  'Darren Reidy',
  'David Byrnes',
  'David Ryan',
  'Declan Keogh',
  'Diarmuid Tarrant',
  'Doreen Matthews',
  'Dylan Glynn',
  'Edward Delany',
  'Egydio Albanese',
  'Erika Karolova',
  'Fabio Jardim',
  'Ger Bolger',
  'Hendrik Niemand',
  'Ian McManus',
  'Istvan Kamondi',
  'James Morgan',
  'Jamie Punch',
  'Ken Smyth',
  'Kevin McCabe',
  'Krzysztof Brykala',
  'Kyle Byrne',
  "Louise O'Sullivan",
  'Maciej Zywot',
  'Mathys Mathey',
  'Mark Forde',
  'Naga Manoj',
  'Neil Macartney',
  'Nika Vadachkoria',
  'Paddy Butler',
  'Paul Cotter',
  'Paul Walsh',
  'Pauline Sourdille',
  'Philip Byrne',
  'Piotr Borawski',
  'Richard Daly',
  'Richard Hubinette',
  'Sam Higgins',
  'Seamus Harding',
  'Sean Sutcliffe',
  'Sakib Hossain',
  'Shahariar Khan',
  'Shah Sami',
  'Lee Hurley',
]

export const serviceCategories = {
  Prelims: [
    'Miscellaneous',
    'Document Generation',
    'Meeting',
    'Project Management',
    'Variations',
    'Receipt Verification',
  ],
  Scope: [
    'Software Engineering',
    'SAT',
    'ACP generation',
    'ACP Software/Graphics',
    'Snags',
    'Panel Modifications',
    'HLC',
    'SFAT',
    'HFAT',
    'Software Design',
    'Hardware Design',
    'Hardware Design Documents',
    'Miscellaneous',
    'VTOPs',
    'Document Generation',
  ],
  'N.A': [
    'Annual Leave',
    'Sick Leave',
    'Bank Holiday',
    'Training',
    'Site Induction',
    'Estimating new jobs',
    'Days in Lieu',
    'Miscellaneous',
  ],
}

export const projects = [
  {
    code: 'PRJ-001',
    name: 'Orion Control Upgrade',
    scopes: ['Control Software', 'Commissioning', 'Documentation'],
  },
  {
    code: 'PRJ-002',
    name: 'Lumen Energy Rollout',
    scopes: ['Site Survey', 'Panel Build', 'Software Deployment'],
  },
  {
    code: 'PRJ-003',
    name: 'Helix Safety Retrofit',
    scopes: ['Risk Assessment', 'On-site FAT', 'Testing'],
  },
  {
    code: 'PRJ-004',
    name: 'Atlas HVAC Modernisation',
    scopes: ['PLC Programming', 'Graphics', 'Training'],
  },
]

export const timeOptions = Array.from({ length: 24 * 4 + 1 }, (_, idx) => {
  const totalMinutes = idx * 15
  const hours = String(Math.floor(totalMinutes / 60)).padStart(2, '0')
  const minutes = String(totalMinutes % 60).padStart(2, '0')
  return `${hours}:${minutes}`
})
